export const EN_LANGUAGE = "English";
export const AM_LANGUAGE = "አማርኛ";
export const LANGUAGES = [EN_LANGUAGE, AM_LANGUAGE];
export const USER = "USER";
export const SETTING = "setting";
export const CANCEL = "cancel";
export const FORMS = "ቅጾች";
export const MAX_IMG_SIZE = 8;
// export const ADMIN_TELEGRAM_ID = 430099839; //admin nebiyu chat id
export const ADMIN_TELEGRAM_ID = 430099839; //admin chat id
export const CHANNEL_ID = -1001668303230;
export const ADMIN_TELEGRAM_USERNAME = "Nebaaaazzzz";
// export const ADMIN_TELEGRAM_USERNAME = "Nebaaaazzzz";
export const ADMIN_PHONE_NUMBER = "+251914514657";
export const ABOUT_US = "About Us";
export const TERMS_OF_USE = "Terms of Use";
/* house types */
export const SUBMIT = "Submit";
export const ADMIN = "ADMIN";
